/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers';
import { Provider, TransactionRequest } from '@ethersproject/providers';
import type { SettingsCenterErrors, SettingsCenterErrorsInterface } from '../SettingsCenterErrors';

const _abi = [
  {
    inputs: [],
    name: 'AuditorIndexError',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'deadline',
        type: 'uint256',
      },
    ],
    name: 'ExpiredCertificate',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InsufficientBalanceForAction',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidDepositAmount',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidIssuer',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidRollupFee',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidRollupSize',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NotChanged',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NumInputsGreaterThanZero',
    type: 'error',
  },
  {
    inputs: [],
    name: 'RollupSizeNotPowerOfTwo',
    type: 'error',
  },
  {
    inputs: [],
    name: 'RollupSizeTooSmall',
    type: 'error',
  },
  {
    inputs: [],
    name: 'UnauthorizedRole',
    type: 'error',
  },
];

const _bytecode =
  '0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212207143859eab0f0ca255f010ea77aaf78b04e2405ec69cfe5d6f29093f51c985e064736f6c63430008140033';

type SettingsCenterErrorsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SettingsCenterErrorsConstructorParams,
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SettingsCenterErrors__factory extends ContractFactory {
  constructor(...args: SettingsCenterErrorsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = 'SettingsCenterErrors';
  }

  deploy(overrides?: Overrides & { from?: string | Promise<string> }): Promise<SettingsCenterErrors> {
    return super.deploy(overrides || {}) as Promise<SettingsCenterErrors>;
  }
  getDeployTransaction(overrides?: Overrides & { from?: string | Promise<string> }): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SettingsCenterErrors {
    return super.attach(address) as SettingsCenterErrors;
  }
  connect(signer: Signer): SettingsCenterErrors__factory {
    return super.connect(signer) as SettingsCenterErrors__factory;
  }
  static readonly contractName: 'SettingsCenterErrors';
  public readonly contractName: 'SettingsCenterErrors';
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SettingsCenterErrorsInterface {
    return new utils.Interface(_abi) as SettingsCenterErrorsInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): SettingsCenterErrors {
    return new Contract(address, _abi, signerOrProvider) as SettingsCenterErrors;
  }
}
