export enum MAIN_TOKEN {
  ETH = 'ETH',
  BSC = 'BNB',
  POLYGON = 'MATIC',
  AVALANCHE = 'AVAX',
  FANTOM = 'FTM',
  MOONBASE = 'DEV',
  ETH_BRIDGE = 'mETH',
  BSC_BRIDGE = 'mBNB',
  POLYGON_BRIDGE = 'mMATIC',
  AVALANCHE_BRIDGE = 'mAVAX',
  FANTOM_BRIDGE = 'mFTM',
  MOONBASE_BRIDGE = 'mDEV',
}

export enum ERC20_TOKEN {
  MTT = 'MTT',
  MUSD = 'mUSD',
}
