module.exports = {
  skipFiles: [
    'mocks/DummySanctions.sol',
    'mocks/token/TestToken.sol',
    'mocks/proxy/DummyCelerMessageBus.sol',
    'mocks/proxy/DummyLZEndpoint.sol',
    'mocks/proxy/DummyAxelarGateway.sol',
    'mocks/proxy/DummyAxelarGasService.sol',
    'core/deposit/layerzero/relay/lzApp/LzApp.sol',
    'core/deposit/layerzero/relay/lzApp/NonblockingLzApp.sol',
    'core/deposit/axelar/relay/IAxelarExecutable.sol',
    'libs/utils/ZeroCopySink.sol',
    'libs/utils/ZeroCopySource.sol',
    'libs/utils/Utils.sol',
    'libs/verifiers/Pairing.sol',
    'libs/verifiers/VerifierLib.sol',
    'libs/verifiers/Rollup1Verifier.sol',
    'libs/verifiers/Rollup4Verifier.sol',
    'libs/verifiers/Rollup16Verifier.sol',
    'libs/verifiers/Transaction1x0Verifier.sol',
    'libs/verifiers/Transaction1x1Verifier.sol',
    'libs/verifiers/Transaction1x2Verifier.sol',
    'libs/verifiers/Transaction2x0Verifier.sol',
    'libs/verifiers/Transaction2x1Verifier.sol',
    'libs/verifiers/Transaction2x2Verifier.sol',
  ],
};
