[profile.default]
src = 'contracts'
libs = ["lib"]
out = 'foundry/out'
test = 'test'
cache = true
cache_path = 'foundry/cache'
match_path = '**/test/**/*.test.sol'
solc = "0.8.26"
via_ir = true

remappings = [
  "wormhole-sdk/=lib/wormhole-sdk/src/",
  "IERC20/=lib/wormhole-sdk/src/interfaces/token/",
]
