[executor]
enable_auto_refund = false

[[service]]
signer_keystore = "/home/eric/x-project/testnet/v2/celer/executor/eth-ks/signer.json"
signer_passphrase = "Xmgh9369"

  [[service.contracts]]
  chain_id = 5
  address = "0x122BF2892fDc2304175642802AA53241ad8aAC3e"
  allow_sender_groups = "goerli-bsctestnet-ETH-6"

  [[service.contracts]]
  chain_id = 97
  address = "0x24Fd8ebc811997E1a362065944CaD87064E44466"
  allow_sender_groups = "goerli-bsctestnet-ETH-6"

  [[service.contracts]]
  chain_id = 5
  address = "0xA1F81f4ce2C7bc128D4B13070D342B22d3415293"
  allow_sender_groups = "goerli-bsctestnet-mBNB-6"

  [[service.contracts]]
  chain_id = 97
  address = "0x71559b31F8AB71bfB5F6F4dAB9C24dA2078e80F1"
  allow_sender_groups = "goerli-bsctestnet-mBNB-6"

  [[service.contracts]]
  chain_id = 5
  address = "0x26b8375Bd8cD77956f0788AAd27933Cc227b2583"
  allow_sender_groups = "goerli-bsctestnet-MTT-6"

  [[service.contracts]]
  chain_id = 97
  address = "0x30B6D3Cb79dc1297F875C501d2b716e04C2c82b4"
  allow_sender_groups = "goerli-bsctestnet-MTT-6"

  [[service.contracts]]
  chain_id = 5
  address = "0x87837a918C7e48DA2f2c98aAE42A8745b4320464"
  allow_sender_groups = "goerli-bsctestnet-mUSD-6"

  [[service.contracts]]
  chain_id = 97
  address = "0xD2913fF5DB7B9a26f66eb9999677F9805ac40aFC"
  allow_sender_groups = "goerli-bsctestnet-mUSD-6"

  [[service.contracts]]
  chain_id = 5
  address = "0xc66de4f0df8Ad1a40A8F7A333DcE1e8dF3ffeeaa"
  allow_sender_groups = "goerli-polygontestnet-ETH-6"

  [[service.contracts]]
  chain_id = 80001
  address = "0x24Fd8ebc811997E1a362065944CaD87064E44466"
  allow_sender_groups = "goerli-polygontestnet-ETH-6"

  [[service.contracts]]
  chain_id = 5
  address = "0xB69B84Db43003B8e50c2f3e90d36E153B18773AD"
  allow_sender_groups = "goerli-polygontestnet-MATIC-6"

  [[service.contracts]]
  chain_id = 80001
  address = "0x71559b31F8AB71bfB5F6F4dAB9C24dA2078e80F1"
  allow_sender_groups = "goerli-polygontestnet-MATIC-6"

  [[service.contracts]]
  chain_id = 5
  address = "0xD7341471aC5Ca0d12773069C28fefbA0353eDed1"
  allow_sender_groups = "goerli-polygontestnet-MTT-6"

  [[service.contracts]]
  chain_id = 80001
  address = "0x30B6D3Cb79dc1297F875C501d2b716e04C2c82b4"
  allow_sender_groups = "goerli-polygontestnet-MTT-6"

  [[service.contracts]]
  chain_id = 5
  address = "0xeeab9757eaC6bfC7D1915DBd1dB15A562D76B755"
  allow_sender_groups = "goerli-polygontestnet-mUSD-6"

  [[service.contracts]]
  chain_id = 80001
  address = "0xD2913fF5DB7B9a26f66eb9999677F9805ac40aFC"
  allow_sender_groups = "goerli-polygontestnet-mUSD-6"

  [[service.contracts]]
  chain_id = 5
  address = "0x7c7b256a970d486AA8d33BD11B21f5520f9D25d3"
  allow_sender_groups = "goerli-avalanchetestnet-ETH-6"

  [[service.contracts]]
  chain_id = 43113
  address = "0x24Fd8ebc811997E1a362065944CaD87064E44466"
  allow_sender_groups = "goerli-avalanchetestnet-ETH-6"

  [[service.contracts]]
  chain_id = 5
  address = "0x1DD1e6D7751885737507ab5Fa9998fc47888D139"
  allow_sender_groups = "goerli-avalanchetestnet-mAVAX-6"

  [[service.contracts]]
  chain_id = 43113
  address = "0x71559b31F8AB71bfB5F6F4dAB9C24dA2078e80F1"
  allow_sender_groups = "goerli-avalanchetestnet-mAVAX-6"

  [[service.contracts]]
  chain_id = 5
  address = "0xcED692508DD2444757c1eFdd3CC4D8500B202b12"
  allow_sender_groups = "goerli-avalanchetestnet-MTT-6"

  [[service.contracts]]
  chain_id = 43113
  address = "0x30B6D3Cb79dc1297F875C501d2b716e04C2c82b4"
  allow_sender_groups = "goerli-avalanchetestnet-MTT-6"

  [[service.contracts]]
  chain_id = 5
  address = "0xCD78b58A362CE64d48ED7b96C47f5cc7d26D721A"
  allow_sender_groups = "goerli-avalanchetestnet-mUSD-6"

  [[service.contracts]]
  chain_id = 43113
  address = "0xD2913fF5DB7B9a26f66eb9999677F9805ac40aFC"
  allow_sender_groups = "goerli-avalanchetestnet-mUSD-6"

  [[service.contracts]]
  chain_id = 5
  address = "0x55e6592dF28722D71aF807efC86BE530db1dFC0C"
  allow_sender_groups = "goerli-fantomtestnet-ETH-6"

  [[service.contracts]]
  chain_id = 4002
  address = "0x24Fd8ebc811997E1a362065944CaD87064E44466"
  allow_sender_groups = "goerli-fantomtestnet-ETH-6"

  [[service.contracts]]
  chain_id = 5
  address = "0x1a91751a48ae787B3d8b40039b2dC53285B1E2ed"
  allow_sender_groups = "goerli-fantomtestnet-mFTM-6"

  [[service.contracts]]
  chain_id = 4002
  address = "0x71559b31F8AB71bfB5F6F4dAB9C24dA2078e80F1"
  allow_sender_groups = "goerli-fantomtestnet-mFTM-6"

  [[service.contracts]]
  chain_id = 5
  address = "0x26080F7Cc99d7091fc3DEC7950Ecd1c72d641C57"
  allow_sender_groups = "goerli-fantomtestnet-MTT-6"

  [[service.contracts]]
  chain_id = 4002
  address = "0x30B6D3Cb79dc1297F875C501d2b716e04C2c82b4"
  allow_sender_groups = "goerli-fantomtestnet-MTT-6"

  [[service.contracts]]
  chain_id = 5
  address = "0xa5FCC84206B408cfd09c103603D6aD52f0Ea43B6"
  allow_sender_groups = "goerli-fantomtestnet-mUSD-6"

  [[service.contracts]]
  chain_id = 4002
  address = "0xD2913fF5DB7B9a26f66eb9999677F9805ac40aFC"
  allow_sender_groups = "goerli-fantomtestnet-mUSD-6"

  [[service.contract_sender_groups]]
  name = "goerli-bsctestnet-ETH-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x122BF2892fDc2304175642802AA53241ad8aAC3e"

    [[service.contract_sender_groups.allow]]
    chain_id = 97
    address = "0x24Fd8ebc811997E1a362065944CaD87064E44466"

  [[service.contract_sender_groups]]
  name = "goerli-bsctestnet-mBNB-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xA1F81f4ce2C7bc128D4B13070D342B22d3415293"

    [[service.contract_sender_groups.allow]]
    chain_id = 97
    address = "0x71559b31F8AB71bfB5F6F4dAB9C24dA2078e80F1"

  [[service.contract_sender_groups]]
  name = "goerli-bsctestnet-MTT-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x26b8375Bd8cD77956f0788AAd27933Cc227b2583"

    [[service.contract_sender_groups.allow]]
    chain_id = 97
    address = "0x30B6D3Cb79dc1297F875C501d2b716e04C2c82b4"

  [[service.contract_sender_groups]]
  name = "goerli-bsctestnet-mUSD-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x87837a918C7e48DA2f2c98aAE42A8745b4320464"

    [[service.contract_sender_groups.allow]]
    chain_id = 97
    address = "0xD2913fF5DB7B9a26f66eb9999677F9805ac40aFC"

  [[service.contract_sender_groups]]
  name = "goerli-polygontestnet-ETH-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xc66de4f0df8Ad1a40A8F7A333DcE1e8dF3ffeeaa"

    [[service.contract_sender_groups.allow]]
    chain_id = 80001
    address = "0x24Fd8ebc811997E1a362065944CaD87064E44466"

  [[service.contract_sender_groups]]
  name = "goerli-polygontestnet-MATIC-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xB69B84Db43003B8e50c2f3e90d36E153B18773AD"

    [[service.contract_sender_groups.allow]]
    chain_id = 80001
    address = "0x71559b31F8AB71bfB5F6F4dAB9C24dA2078e80F1"

  [[service.contract_sender_groups]]
  name = "goerli-polygontestnet-MTT-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xD7341471aC5Ca0d12773069C28fefbA0353eDed1"

    [[service.contract_sender_groups.allow]]
    chain_id = 80001
    address = "0x30B6D3Cb79dc1297F875C501d2b716e04C2c82b4"

  [[service.contract_sender_groups]]
  name = "goerli-polygontestnet-mUSD-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xeeab9757eaC6bfC7D1915DBd1dB15A562D76B755"

    [[service.contract_sender_groups.allow]]
    chain_id = 80001
    address = "0xD2913fF5DB7B9a26f66eb9999677F9805ac40aFC"

  [[service.contract_sender_groups]]
  name = "goerli-avalanchetestnet-ETH-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x7c7b256a970d486AA8d33BD11B21f5520f9D25d3"

    [[service.contract_sender_groups.allow]]
    chain_id = 43113
    address = "0x24Fd8ebc811997E1a362065944CaD87064E44466"

  [[service.contract_sender_groups]]
  name = "goerli-avalanchetestnet-mAVAX-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x1DD1e6D7751885737507ab5Fa9998fc47888D139"

    [[service.contract_sender_groups.allow]]
    chain_id = 43113
    address = "0x71559b31F8AB71bfB5F6F4dAB9C24dA2078e80F1"

  [[service.contract_sender_groups]]
  name = "goerli-avalanchetestnet-MTT-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xcED692508DD2444757c1eFdd3CC4D8500B202b12"

    [[service.contract_sender_groups.allow]]
    chain_id = 43113
    address = "0x30B6D3Cb79dc1297F875C501d2b716e04C2c82b4"

  [[service.contract_sender_groups]]
  name = "goerli-avalanchetestnet-mUSD-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xCD78b58A362CE64d48ED7b96C47f5cc7d26D721A"

    [[service.contract_sender_groups.allow]]
    chain_id = 43113
    address = "0xD2913fF5DB7B9a26f66eb9999677F9805ac40aFC"

  [[service.contract_sender_groups]]
  name = "goerli-fantomtestnet-ETH-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x55e6592dF28722D71aF807efC86BE530db1dFC0C"

    [[service.contract_sender_groups.allow]]
    chain_id = 4002
    address = "0x24Fd8ebc811997E1a362065944CaD87064E44466"

  [[service.contract_sender_groups]]
  name = "goerli-fantomtestnet-mFTM-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x1a91751a48ae787B3d8b40039b2dC53285B1E2ed"

    [[service.contract_sender_groups.allow]]
    chain_id = 4002
    address = "0x71559b31F8AB71bfB5F6F4dAB9C24dA2078e80F1"

  [[service.contract_sender_groups]]
  name = "goerli-fantomtestnet-MTT-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x26080F7Cc99d7091fc3DEC7950Ecd1c72d641C57"

    [[service.contract_sender_groups.allow]]
    chain_id = 4002
    address = "0x30B6D3Cb79dc1297F875C501d2b716e04C2c82b4"

  [[service.contract_sender_groups]]
  name = "goerli-fantomtestnet-mUSD-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xa5FCC84206B408cfd09c103603D6aD52f0Ea43B6"

    [[service.contract_sender_groups.allow]]
    chain_id = 4002
    address = "0xD2913fF5DB7B9a26f66eb9999677F9805ac40aFC"

[sgnd]
sgn_grpc = "cbridge-v2-test.celer.network:9094"
gateway_grpc = "cbridge-v2-test.celer.network:9094"

[db]
url = "localhost:26257"
