[executor]
enable_auto_refund = false

[[service]]
signer_keystore = "/home/eric/x-project/testnet/v2/celer/executor/eth-ks/signer.json"
signer_passphrase = "Xmgh9369"

  [[service.contracts]]
  chain_id = 80001
  address = "0x9Fe3b52965331c3b204935d7b4B93dBC83EfD07D"
  allow_sender_groups = "bsctestnet-polygontestnet-MTT-6"

  [[service.contracts]]
  chain_id = 97
  address = "0xFAbb592D2570F941b0c7A2994Ed68703F5Af5d27"
  allow_sender_groups = "bsctestnet-polygontestnet-MTT-6"

  [[service.contracts]]
  chain_id = 80001
  address = "0x674D7c361643B968Cf1ef37b08200a9c898201fF"
  allow_sender_groups = "bsctestnet-polygontestnet-mUSD-6"

  [[service.contracts]]
  chain_id = 97
  address = "0xA60F76C2C7c4589695d1515529C733B9BA53E53e"
  allow_sender_groups = "bsctestnet-polygontestnet-mUSD-6"

  [[service.contract_sender_groups]]
  name = "bsctestnet-polygontestnet-MTT-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 80001
    address = "0x9Fe3b52965331c3b204935d7b4B93dBC83EfD07D"

    [[service.contract_sender_groups.allow]]
    chain_id = 97
    address = "0xFAbb592D2570F941b0c7A2994Ed68703F5Af5d27"

  [[service.contract_sender_groups]]
  name = "bsctestnet-polygontestnet-mUSD-6"

    [[service.contract_sender_groups.allow]]
    chain_id = 80001
    address = "0x674D7c361643B968Cf1ef37b08200a9c898201fF"

    [[service.contract_sender_groups.allow]]
    chain_id = 97
    address = "0xA60F76C2C7c4589695d1515529C733B9BA53E53e"

[sgnd]
sgn_grpc = "cbridge-v2-test.celer.network:9094"
gateway_grpc = "cbridge-v2-test.celer.network:9094"

[db]
url = "localhost:26257"
