[executor]
enable_auto_refund = false

[[service]]
signer_keystore = "/home/eric/x-project/testnet/v2/celer/executor/eth-ks/signer.json"
signer_passphrase = "Xmgh9369"

  [[service.contracts]]
  chain_id = 5
  address = "0xb1bDDa694D2ebbcb0a5Cb6c6cFc0a1F0B759b19A"
  allow_sender_groups = "goerli-bsctestnet-ETH-4"

  [[service.contracts]]
  chain_id = 97
  address = "0xBA2ec3001f2268C8fdf9D2D4AE98377C9ec1C4B3"
  allow_sender_groups = "goerli-bsctestnet-ETH-4"

  [[service.contracts]]
  chain_id = 5
  address = "0x6DBcDe05cc1eCF4bB023EF953245C26966bF9B06"
  allow_sender_groups = "goerli-bsctestnet-mBNB-4"

  [[service.contracts]]
  chain_id = 97
  address = "0xD3dca9802421F5ffBbc4E8D6cb90BaA1Ec25010e"
  allow_sender_groups = "goerli-bsctestnet-mBNB-4"

  [[service.contracts]]
  chain_id = 5
  address = "0x7224B97833737baB521C8EbF0E706fDCAAF5eA82"
  allow_sender_groups = "goerli-bsctestnet-MTT-4"

  [[service.contracts]]
  chain_id = 97
  address = "0xc156D1279cdb8574318fc26af0F20dd84Cbf7c2e"
  allow_sender_groups = "goerli-bsctestnet-MTT-4"

  [[service.contracts]]
  chain_id = 5
  address = "0xaa08C8ee7d3104Ea86F952C652813CF831230887"
  allow_sender_groups = "goerli-bsctestnet-mUSD-4"

  [[service.contracts]]
  chain_id = 97
  address = "0xa3496E53d53080b157c901598D4f230CBb4f0552"
  allow_sender_groups = "goerli-bsctestnet-mUSD-4"

  [[service.contracts]]
  chain_id = 5
  address = "0x2076f17A512a423B9e034ff8816728064C03cA11"
  allow_sender_groups = "goerli-polygontestnet-ETH-4"

  [[service.contracts]]
  chain_id = 80_001
  address = "0x91F66531aB71fB3021C163e880fBbf650a258D6E"
  allow_sender_groups = "goerli-polygontestnet-ETH-4"

  [[service.contracts]]
  chain_id = 5
  address = "0x59Ac55E3899CD043FD19fF46189E45838e1cF9b7"
  allow_sender_groups = "goerli-polygontestnet-MATIC-4"

  [[service.contracts]]
  chain_id = 80_001
  address = "0x2EBD101b5BA96FCAC9dDC2b1Ca34A3A08aAc9fa7"
  allow_sender_groups = "goerli-polygontestnet-MATIC-4"

  [[service.contracts]]
  chain_id = 5
  address = "0x3DBa1eD5083b2f1CBb7791fc2c5FEC5061da3379"
  allow_sender_groups = "goerli-polygontestnet-MTT-4"

  [[service.contracts]]
  chain_id = 80_001
  address = "0xcFF9f83Ff6c75e6Eb72B9f9c99a4F064e8AeD207"
  allow_sender_groups = "goerli-polygontestnet-MTT-4"

  [[service.contracts]]
  chain_id = 5
  address = "0xb8ad1Affb5E97d97948fd25385f9987953303D16"
  allow_sender_groups = "goerli-polygontestnet-mUSD-4"

  [[service.contracts]]
  chain_id = 80_001
  address = "0xd17c921527610a547C1E604b16b8583aE493bD1a"
  allow_sender_groups = "goerli-polygontestnet-mUSD-4"

  [[service.contracts]]
  chain_id = 5
  address = "0x77e41475D61B2b2fcc04162B09529703072b43d7"
  allow_sender_groups = "goerli-avalanchetestnet-ETH-4"

  [[service.contracts]]
  chain_id = 43_113
  address = "0x91919809625B8EDF6A9769ef6eEA62FD159DCfA0"
  allow_sender_groups = "goerli-avalanchetestnet-ETH-4"

  [[service.contracts]]
  chain_id = 5
  address = "0xab9a47Ca1b54C7478dc874cA9d09761f9192E6D8"
  allow_sender_groups = "goerli-avalanchetestnet-mAVAX-4"

  [[service.contracts]]
  chain_id = 43_113
  address = "0x9a9C0dbE132518FbA1DD961BbDb7A0c8C72841Ae"
  allow_sender_groups = "goerli-avalanchetestnet-mAVAX-4"

  [[service.contracts]]
  chain_id = 5
  address = "0xc55F56709EF1f80a2a627A5363Fd48b47BE0C551"
  allow_sender_groups = "goerli-avalanchetestnet-MTT-4"

  [[service.contracts]]
  chain_id = 43_113
  address = "0x1885F188aCAF875225C28f6fC10D0f3c4Ad8F533"
  allow_sender_groups = "goerli-avalanchetestnet-MTT-4"

  [[service.contracts]]
  chain_id = 5
  address = "0x12c677208A5bF9C040Bc0AF563b886c5af6DAB5D"
  allow_sender_groups = "goerli-avalanchetestnet-mUSD-4"

  [[service.contracts]]
  chain_id = 43_113
  address = "0xF945fD7AbA82eB83195166F6a485c63185Ef878C"
  allow_sender_groups = "goerli-avalanchetestnet-mUSD-4"

  [[service.contracts]]
  chain_id = 5
  address = "0xD4b4fe6B065fC3b29B55a7b8afBf1C18306ffED3"
  allow_sender_groups = "goerli-fantomtestnet-ETH-4"

  [[service.contracts]]
  chain_id = 4_002
  address = "0x8367bE9aFC0ebbEf82Fdf4DD0a2Ca8E9b4F244D9"
  allow_sender_groups = "goerli-fantomtestnet-ETH-4"

  [[service.contracts]]
  chain_id = 5
  address = "0xDD6093a1479C31e64c5eC83B6a5AAA79d623D481"
  allow_sender_groups = "goerli-fantomtestnet-mFTM-4"

  [[service.contracts]]
  chain_id = 4_002
  address = "0x5deD1A7A5609b8DE402583c08a40956842E17C3f"
  allow_sender_groups = "goerli-fantomtestnet-mFTM-4"

  [[service.contracts]]
  chain_id = 5
  address = "0x62d9Cb213c2173eF6b95F2212cE282D2D866b8D5"
  allow_sender_groups = "goerli-fantomtestnet-MTT-4"

  [[service.contracts]]
  chain_id = 4_002
  address = "0x396cD19a619caF2c32908EF7Cb954423fdF4DE20"
  allow_sender_groups = "goerli-fantomtestnet-MTT-4"

  [[service.contracts]]
  chain_id = 5
  address = "0xB5ca2f417cD53f176FA77787B05023Ee17aEd342"
  allow_sender_groups = "goerli-fantomtestnet-mUSD-4"

  [[service.contracts]]
  chain_id = 4_002
  address = "0x56E466Bc3d0278c7F1B724A90bfDBA6e86419eB4"
  allow_sender_groups = "goerli-fantomtestnet-mUSD-4"

  [[service.contract_sender_groups]]
  name = "goerli-bsctestnet-ETH-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xb1bDDa694D2ebbcb0a5Cb6c6cFc0a1F0B759b19A"

    [[service.contract_sender_groups.allow]]
    chain_id = 97
    address = "0xBA2ec3001f2268C8fdf9D2D4AE98377C9ec1C4B3"

  [[service.contract_sender_groups]]
  name = "goerli-bsctestnet-mBNB-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x6DBcDe05cc1eCF4bB023EF953245C26966bF9B06"

    [[service.contract_sender_groups.allow]]
    chain_id = 97
    address = "0xD3dca9802421F5ffBbc4E8D6cb90BaA1Ec25010e"

  [[service.contract_sender_groups]]
  name = "goerli-bsctestnet-MTT-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x7224B97833737baB521C8EbF0E706fDCAAF5eA82"

    [[service.contract_sender_groups.allow]]
    chain_id = 97
    address = "0xc156D1279cdb8574318fc26af0F20dd84Cbf7c2e"

  [[service.contract_sender_groups]]
  name = "goerli-bsctestnet-mUSD-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xaa08C8ee7d3104Ea86F952C652813CF831230887"

    [[service.contract_sender_groups.allow]]
    chain_id = 97
    address = "0xa3496E53d53080b157c901598D4f230CBb4f0552"

  [[service.contract_sender_groups]]
  name = "goerli-polygontestnet-ETH-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x2076f17A512a423B9e034ff8816728064C03cA11"

    [[service.contract_sender_groups.allow]]
    chain_id = 80_001
    address = "0x91F66531aB71fB3021C163e880fBbf650a258D6E"

  [[service.contract_sender_groups]]
  name = "goerli-polygontestnet-MATIC-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x59Ac55E3899CD043FD19fF46189E45838e1cF9b7"

    [[service.contract_sender_groups.allow]]
    chain_id = 80_001
    address = "0x2EBD101b5BA96FCAC9dDC2b1Ca34A3A08aAc9fa7"

  [[service.contract_sender_groups]]
  name = "goerli-polygontestnet-MTT-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x3DBa1eD5083b2f1CBb7791fc2c5FEC5061da3379"

    [[service.contract_sender_groups.allow]]
    chain_id = 80_001
    address = "0xcFF9f83Ff6c75e6Eb72B9f9c99a4F064e8AeD207"

  [[service.contract_sender_groups]]
  name = "goerli-polygontestnet-mUSD-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xb8ad1Affb5E97d97948fd25385f9987953303D16"

    [[service.contract_sender_groups.allow]]
    chain_id = 80_001
    address = "0xd17c921527610a547C1E604b16b8583aE493bD1a"

  [[service.contract_sender_groups]]
  name = "goerli-avalanchetestnet-ETH-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x77e41475D61B2b2fcc04162B09529703072b43d7"

    [[service.contract_sender_groups.allow]]
    chain_id = 43_113
    address = "0x91919809625B8EDF6A9769ef6eEA62FD159DCfA0"

  [[service.contract_sender_groups]]
  name = "goerli-avalanchetestnet-mAVAX-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xab9a47Ca1b54C7478dc874cA9d09761f9192E6D8"

    [[service.contract_sender_groups.allow]]
    chain_id = 43_113
    address = "0x9a9C0dbE132518FbA1DD961BbDb7A0c8C72841Ae"

  [[service.contract_sender_groups]]
  name = "goerli-avalanchetestnet-MTT-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xc55F56709EF1f80a2a627A5363Fd48b47BE0C551"

    [[service.contract_sender_groups.allow]]
    chain_id = 43_113
    address = "0x1885F188aCAF875225C28f6fC10D0f3c4Ad8F533"

  [[service.contract_sender_groups]]
  name = "goerli-avalanchetestnet-mUSD-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x12c677208A5bF9C040Bc0AF563b886c5af6DAB5D"

    [[service.contract_sender_groups.allow]]
    chain_id = 43_113
    address = "0xF945fD7AbA82eB83195166F6a485c63185Ef878C"

  [[service.contract_sender_groups]]
  name = "goerli-fantomtestnet-ETH-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xD4b4fe6B065fC3b29B55a7b8afBf1C18306ffED3"

    [[service.contract_sender_groups.allow]]
    chain_id = 4_002
    address = "0x8367bE9aFC0ebbEf82Fdf4DD0a2Ca8E9b4F244D9"

  [[service.contract_sender_groups]]
  name = "goerli-fantomtestnet-mFTM-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xDD6093a1479C31e64c5eC83B6a5AAA79d623D481"

    [[service.contract_sender_groups.allow]]
    chain_id = 4_002
    address = "0x5deD1A7A5609b8DE402583c08a40956842E17C3f"

  [[service.contract_sender_groups]]
  name = "goerli-fantomtestnet-MTT-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0x62d9Cb213c2173eF6b95F2212cE282D2D866b8D5"

    [[service.contract_sender_groups.allow]]
    chain_id = 4_002
    address = "0x396cD19a619caF2c32908EF7Cb954423fdF4DE20"

  [[service.contract_sender_groups]]
  name = "goerli-fantomtestnet-mUSD-4"

    [[service.contract_sender_groups.allow]]
    chain_id = 5
    address = "0xB5ca2f417cD53f176FA77787B05023Ee17aEd342"

    [[service.contract_sender_groups.allow]]
    chain_id = 4_002
    address = "0x56E466Bc3d0278c7F1B724A90bfDBA6e86419eB4"

[sgnd]
sgn_grpc = "cbridge-v2-test.celer.network:9094"
gateway_grpc = "cbridge-v2-test.celer.network:9094"

[db]
url = "localhost:26257"
